### ISSUE TITLE
model parameter key from Baidu can't match parameter in code

### ISSUE THREAD

**Issue by Jerry2990** [MichaelFan01/STDC-Seg#22]

**Comment by Jerry2990** [comment]
Thank you for sharing. However, All six weights can't match when evaluating. Are my settings wrong? 
Look forward for your reply.

**Comment by minhna1112** [comment]
How did you download the weights from Baidu? It seems to me that Baidu does not allow registration for non-Chinese mobile numbers, or even non-QQ email accounts

**Comment by MichaelFan01** [comment]
> How did you download the weights from Baidu? It seems to me that Baidu does not allow registration for non-Chinese mobile numbers, or even non-QQ email accounts

Here is google drive link: https://drive.google.com/drive/folders/1wROFwRt8qWHD4jSo8Zu1gp1d6oYJ3ns1

**Comment by MichaelFan01** [comment]
> How did you download the weights from Baidu? It seems to me that Baidu does not allow registration for non-Chinese mobile numbers, or even non-QQ email accounts

Here is the google drive link:https://drive.google.com/drive/folders/1wROFwRt8qWHD4jSo8Zu1gp1d6oYJ3ns1?usp=sharing

**Comment by MichaelFan01** [comment]
> Thank you for sharing. However, All six weights can't match when evaluating. Are my settings wrong?
> Look forward for your reply.

What's the error message?
