### ISSUE TITLE
Cannot download weights from Baidu

### ISSUE THREAD

**Issue by minhna1112** [MichaelFan01/STDC-Seg#23]
I have tried multiple ways to download the weights file from your Baidu links.

The site requires signing in for download; however, it seems impossible for non-Chinese users to sign up for an account on Baidu.

I might suggest that you would want to upload the weights on different storage platform (Google Drive, OneDrive, etc), so that it would be more accessible to other users.

Sincerely thanks

**Comment by MichaelFan01** [comment]
> I have tried multiple ways to download the weights file from your Baidu links.
> 
> The site requires signing in for download; however, it seems impossible for non-Chinese users to sign up for an account on Baidu.
> 
> I might suggest that you would want to upload the weights on different storage platform (Google Drive, OneDrive, etc), so that it would be more accessible to other users.
> 
> Sincerely thanks

https://drive.google.com/drive/folders/1wROFwRt8qWHD4jSo8Zu1gp1d6oYJ3ns1?usp=sharing

**Comment by minhna1112** [comment]
Thank you very much!
