### ISSUE TITLE
关于 在 Network Architecture  中的哪步（Stage）起 作为Detail Guidance 的实验影响

### ISSUE THREAD

**Issue by wy3406** [MichaelFan01/STDC-Seg#32]
@MichaelFan01 ，您好，首先非常感谢您的代码和Paper。
想询问下 Detail Guidance 在 Network Architecture 不同的Stage 对算法性能的影响， （ 即train.py 中的 “use_boundary_X（X指 2 ，4，8，16）”参数的设置）。
1.同时设置 use_boundary_8，use_boundary_16为True，对比 只设置 use_boundary_8 为True时的效果。
2.同时设置 use_boundary_4，use_boundary_8 为True，对比 只设置 use_boundary_8 为True时的效果。
3.对比实验，分别单独设置 use_boundary_4，use_boundary_8 ， use_boundary_16 为True时的效果。

**Comment by MichaelFan01** [comment]
> @MichaelFan01 ，您好，首先非常感谢您的代码和Paper。
> 想询问下 Detail Guidance 在 Network Architecture 不同的Stage 对算法性能的影响， （ 即train.py 中的 “use_boundary_X（X指 2 ，4，8，16）”参数的设置）。
> 1.同时设置 use_boundary_8，use_boundary_16为True，对比 只设置 use_boundary_8 为True时的效果。
> 2.同时设置 use_boundary_4，use_boundary_8 为True，对比 只设置 use_boundary_8 为True时的效果。
> 3.对比实验，分别单独设置 use_boundary_4，use_boundary_8 ， use_boundary_16 为True时的效果。

我的实验结果是只设置 use_boundary_8 为True效果最好，其他任何一个stage为true都会有性能的拖累；初步分析是因为x2, x4这两个stage层数过浅， x16之后已经开始encode 语义信息了，引导其学习空间信息对整体性能会有负面影响；当然也欢迎大家实验有没有更好的做细节引导的方式，这个也是我没有删掉use_boundary_8以外的几个引导参数的原因
