### ISSUE TITLE
关于model_stages.py

### ISSUE THREAD

**Issue by ding-Chen** [MichaelFan01/STDC-Seg#33]
您好，在model_stage.py里面有一行代码不是特别懂，不知道 feat_res2, feat_res4, feat_res8, feat_res16, feat_cp8, feat_cp16 = self.cp(x) 这些准确的指的是什么，您能解答一下吗
![image](https://user-images.githubusercontent.com/85236372/127593593-03f7d2ac-8245-4466-8ebd-dc5d27d7ff5c.png)

**Comment by MichaelFan01** [comment]
> 您好，在model_stage.py里面有一行代码不是特别懂，不知道 feat_res2, feat_res4, feat_res8, feat_res16, feat_cp8, feat_cp16 = self.cp(x) 这些准确的指的是什么，您能解答一下吗
> ![image](https://user-images.githubusercontent.com/85236372/127593593-03f7d2ac-8245-4466-8ebd-dc5d27d7ff5c.png)

参考这个吧 https://github.com/MichaelFan01/STDC-Seg/issues/32

**Comment by ding-Chen** [comment]
好的，我去看看，谢谢您的回答
