### ISSUE TITLE
Unable to open the ImageNet pretrained weight fo the STDC backbone

### ISSUE THREAD

**Issue by Eashwar93** [MichaelFan01/STDC-Seg#39]
Hello there! Thank you very much for open-sourcing your code. It was really a nice paper to read, combining some of the best ideas. I wanted to tryout the model on a custom dateset and I downloaded the ImageNet pre-trained weights just for the STDC Backbone. The .tar files from the the google drive could not be extracted using CLI as well as the Archive Manager. Any help on this would be really great.

The files that I tried to extract are `STDCNet1446_76.47.tar` and `STDCNet813M_73.91.tar` from [here](https://drive.google.com/drive/folders/1wROFwRt8qWHD4jSo8Zu1gp1d6oYJ3ns1)

**Comment by MichaelFan01** [comment]
> STDCNet1446_76.47.tar

STDCNet1446_76.47.tar and STDCNet813M_73.91.tar do not need to extract, you can use them directly~

**Comment by Eashwar93** [comment]
@MichaelFan01 Oh ok. So I can just use them like .pth files. I understand the extensions don't matter in Linux but I just got carried away with the .tar extension

So I guess I can use something like:

`model.load_state_dict(torch.load(PATH))`

Thanks for your clarification
