### ISSUE TITLE
Is the detail loss normal？

### ISSUE THREAD

**Issue by CuberrChen** [MichaelFan01/STDC-Seg#40]
Hello, I'm trying to write my own code to reproduce your paper. I output the sum of boundary losses（boundery_bce_loss + boundery_dice_loss） as shown in the figure below. It seems that its value will not change soon. Is this normal?
![Train_loss_3](https://user-images.githubusercontent.com/44107003/129185380-e7935347-dc28-4b14-940b-a30ef4b163d5.png)

**Comment by MichaelFan01** [comment]
> Hello, I'm trying to write my own code to reproduce your paper. I output the sum of boundary losses（boundery_bce_loss + boundery_dice_loss） as shown in the figure below. It seems that its value will not change soon. Is this normal?
> ![Train_loss_3](https://user-images.githubusercontent.com/44107003/129185380-e7935347-dc28-4b14-940b-a30ef4b163d5.png)

我看了下日志，整体走势跟你的差不多，应该是正常的

**Comment by CuberrChen** [comment]
非常感谢！！！
