### ISSUE TITLE
复现精度很难达到？

### ISSUE THREAD

**Issue by CuberrChen** [MichaelFan01/STDC-Seg#41]
您好，之前向您提过问题。
我正在复现您的论文，但是我复现的结果与论文结果还相差很多。
我采用batchsize 32 iter60000 初始0.01学习率的策略，但是最终只能在cityscapes val上到68的miou。
这里需要提及的是我没有在imagenet上预训练的模型，因此是直接训练的。
我不知道是不是这两个不同点会造成6个点的差异？
或者您能给我给点建议吗？非常感谢！

**Comment by CuberrChen** [comment]
我采用的是STDC2-Seg50

**Comment by CuberrChen** [comment]
另外，我是单卡32G，所以我需要做什么调整比较合理吗？

**Comment by MichaelFan01** [comment]
> 您好，之前向您提过问题。
> 我正在复现您的论文，但是我复现的结果与论文结果还相差很多。
> 我采用batchsize 32 iter60000 初始0.01学习率的策略，但是最终只能在cityscapes val上到68的miou。
> 这里需要提及的是我没有在imagenet上预训练的模型，因此是直接训练的。
> 我不知道是不是这两个不同点会造成6个点的差异？
> 或者您能给我给点建议吗？非常感谢！

最大的问题应该是是没有预训练，Cityscapes训练集也就不到三千张，ImageNe预训练backbone很重要；此外，batchsize32的时候，我也没有找到太好的参数调整，理论上batchsize增加多少倍，初始学习率就增加多少倍，不过前一阵我也调过batchsize32, 确实会掉一点点，我也没找到太好的调参方法。

**Comment by CuberrChen** [comment]
这样嘛..谢谢您的回复。我再去试试

**Comment by Asuna88** [comment]
@CuberrChen 
请问下，作者提供的训练指令中，有个参数选型
--pretrain_path checkpoints/STDCNet813M_73.91.tar

如果使用了这个参数，这样算不算 使用了 “imagenet上预训练的模型“ ？
