### ISSUE TITLE
训练时貌似bn层反向传播报错！

### ISSUE THREAD

**Issue by zzzz737** [MichaelFan01/STDC-Seg#42]
root@oarmbtgcrafltay-v1-7496bcb9dd-phxrs:~/work/STDC-Seg-master# python -m torch.distributed.launch --nproc_per_node=1 train.py
n_workers_train: 0
n_workers_val: 1
use_boundary_2: False
use_boundary_4: False
use_boundary_8: True
use_boundary_16: False
mode: train
self.mode train
self.len train 7551
self.mode val
self.len val 839
use pretrain model ./pretrained/STDCNet813M_73.91.tar
max_iter:  600000
save_iter_sep:  1000
warmup_steps:  1000
Traceback (most recent call last):
  File "train.py", line 446, in <module>
    train()
  File "train.py", line 309, in train
    out, out16, out32, detail8 = net(im)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/distributed.py", line 619, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/work/STDC-Seg-master/models/model_stages.py", line 272, in forward
    feat_res2, feat_res4, feat_res8, feat_res16, feat_cp8, feat_cp16 = self.cp(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/work/STDC-Seg-master/models/model_stages.py", line 141, in forward
    avg = self.conv_avg(avg)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/work/STDC-Seg-master/models/model_stages.py", line 31, in forward
    x = self.bn(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/work/STDC-Seg-master/modules/bn.py", line 119, in forward
    self.training, self.momentum, self.eps, self.activation, self.slope)
RuntimeError: Some elements marked as dirty during the forward method were not returned as output. The inputs that are modified inplace must all be outputs of the Function.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', 'train.py', '--local_rank=0']' returned non-zero exit status 1.

**Comment by GondorFu** [comment]
这个好像是 pytorch 版本的问题

**Comment by zzzz737** [comment]
> 这个好像是 pytorch 版本的问题

我的pytorch版本是1.7，应该用什么版本

**Comment by zzzz737** [comment]
> root@oarmbtgcrafltay-v1-7496bcb9dd-phxrs:~/work/STDC-Seg-master# python -m torch.distributed.launch --nproc_per_node=1 train.py
> n_workers_train: 0
> n_workers_val: 1
> use_boundary_2: False
> use_boundary_4: False
> use_boundary_8: True
> use_boundary_16: False
> mode: train
> self.mode train
> self.len train 7551
> self.mode val
> self.len val 839
> use pretrain model ./pretrained/STDCNet813M_73.91.tar
> max_iter: 600000
> save_iter_sep: 1000
> warmup_steps: 1000
> Traceback (most recent call last):
> File "train.py", line 446, in
> train()
> File "train.py", line 309, in train
> out, out16, out32, detail8 = net(im)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/distributed.py", line 619, in forward
> output = self.module(*inputs[0], **kwargs[0])
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/root/work/STDC-Seg-master/models/model_stages.py", line 272, in forward
> feat_res2, feat_res4, feat_res8, feat_res16, feat_cp8, feat_cp16 = self.cp(x)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/root/work/STDC-Seg-master/models/model_stages.py", line 141, in forward
> avg = self.conv_avg(avg)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/root/work/STDC-Seg-master/models/model_stages.py", line 31, in forward
> x = self.bn(x)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/root/work/STDC-Seg-master/modules/bn.py", line 119, in forward
> self.training, self.momentum, self.eps, self.activation, self.slope)
> RuntimeError: Some elements marked as dirty during the forward method were not returned as output. The inputs that are modified inplace must all be outputs of the Function.
> Traceback (most recent call last):
> File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
> "**main**", mod_spec)
> File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 260, in
> main()
> File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 256, in main
> cmd=cmd)
> subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', 'train.py', '--local_rank=0']' returned non-zero exit status 1.

我把大佬代码中自定义的BN层注释掉了就能训练了
# from modules.bn import InPlaceABNSync as BatchNorm2d
BatchNorm2d = nn.BatchNorm2d
有没有大佬能解释一下是啥问题？ @MichaelFan01

**Comment by GondorFu** [comment]
> > 这个好像是 pytorch 版本的问题
> 
> 我的pytorch版本是1.7，应该用什么版本

用官方推荐的 1.1.0 呀

**Comment by zzzz737** [comment]
> > > 这个好像是 pytorch 版本的问题
> > 
> > 
> > 我的pytorch版本是1.7，应该用什么版本
> 
> 用官方推荐的 1.1.0 呀

我试试，谢谢啦

**Comment by zzzz737** [comment]
> root@oarmbtgcrafltay-v1-7496bcb9dd-phxrs:~/work/STDC-Seg-master# python -m torch.distributed.launch --nproc_per_node=1 train.py
> n_workers_train: 0
> n_workers_val: 1
> use_boundary_2: False
> use_boundary_4: False
> use_boundary_8: True
> use_boundary_16: False
> mode: train
> self.mode train
> self.len train 7551
> self.mode val
> self.len val 839
> use pretrain model ./pretrained/STDCNet813M_73.91.tar
> max_iter: 600000
> save_iter_sep: 1000
> warmup_steps: 1000
> Traceback (most recent call last):
> File "train.py", line 446, in
> train()
> File "train.py", line 309, in train
> out, out16, out32, detail8 = net(im)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/distributed.py", line 619, in forward
> output = self.module(*inputs[0], **kwargs[0])
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/root/work/STDC-Seg-master/models/model_stages.py", line 272, in forward
> feat_res2, feat_res4, feat_res8, feat_res16, feat_cp8, feat_cp16 = self.cp(x)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/root/work/STDC-Seg-master/models/model_stages.py", line 141, in forward
> avg = self.conv_avg(avg)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/root/work/STDC-Seg-master/models/model_stages.py", line 31, in forward
> x = self.bn(x)
> File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/root/work/STDC-Seg-master/modules/bn.py", line 119, in forward
> self.training, self.momentum, self.eps, self.activation, self.slope)
> RuntimeError: Some elements marked as dirty during the forward method were not returned as output. The inputs that are modified inplace must all be outputs of the Function.
> Traceback (most recent call last):
> File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
> "**main**", mod_spec)
> File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 260, in
> main()
> File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 256, in main
> cmd=cmd)
> subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', 'train.py', '--local_rank=0']' returned non-zero exit status 1.

使用pytorch1.1这个问题就不会报错了！！！！！
