### ISSUE TITLE
训练无法正常运行

### ISSUE THREAD

**Issue by mesenlol** [MichaelFan01/STDC-Seg#47]
python -m torch.distributed.launch \
> --nproc_per_node=2 train.py \
> --respath checkpoints/train_STDC1-Seg/ \
> --backbone STDCNet813 \
> --mode train \
> --n_workers_train 12 \
> --n_workers_val 1 \
> --max_iter 60000 \
> --use_boundary_8 True \
> --pretrain_path checkpoints/STDCNet813M_73.91.tar
self.mode train
n_workers_train: 12
n_workers_val: 1
use_boundary_2: False
use_boundary_4: False
use_boundary_8: True
use_boundary_16: False
mode: train
self.mode train
self.len train 2975
self.mode val
self.len train 2975
self.mode val
self.len val 500
self.len val 500
use pretrain model checkpoints/STDCNet813M_73.91.tar
use pretrain model checkpoints/STDCNet813M_73.91.tar
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
按照文档进行训练，到这里就卡住了，一直不动，也没有报错。请问是什么原因，有哪里我设置的不对吗？

**Comment by Asthestarsfalll** [comment]
@mesenlol pytorch版本是多少

**Comment by mesenlol** [comment]
@Asthestarsfalll 
Pytorch 1.1
Python 3.5.6

**Comment by mesenlol** [comment]
@Asthestarsfalll 应该是我的硬件出了什么问题，感谢您的回复，我换台服务器试试

**Comment by ZhaoNan1** [comment]
请问这个问题如何解决的，我现在也遇到了这个问题，就是卡在这里不动

**Comment by Asuna88** [comment]
pytorch版本不匹配，更换即可。
