### ISSUE TITLE
cpu-only inferencing

### ISSUE THREAD

**Issue by seekingdeep** [MichaelFan01/STDC-Seg#5]
@MichaelFan01 Hi there,
in the paper, you stated that STDC uses TensorRT, though it is still interesting to inference using CPU only.

Will STDC be able to inference using CPU?
how much **RAM** will it require for CPU only inferencing?
what is the **FPS** on cpu only?

**Comment by MichaelFan01** [comment]
STDC is not very suitable for CPU only inference, because CPU inference is highly related to FLOPs. 
Mobilenets and Shufflenets are recommended to use on CPU only inference.

**Comment by seekingdeep** [comment]
but can stdc inference using cpu only?

**Comment by MichaelFan01** [comment]
用的话应该也可以跑，不过没做过CPU的实验~

**Comment by seekingdeep** [comment]
great, then i hope that you include cpu inferencing script
