### ISSUE TITLE
请问这个网络支持c++推理部署吗？

### ISSUE THREAD

**Issue by Dandelion111** [MichaelFan01/STDC-Seg#51]
请问这个网络支持c++推理部署吗？

**Comment by MichaelFan01** [comment]
> 请问这个网络支持c++推理部署吗？
转成onnx之后就可以部署了应该

**Comment by Dandelion111** [comment]
> > 请问这个网络支持c++推理部署吗？
> > 转成onnx之后就可以部署了应该

好的，谢谢大哥
