### ISSUE TITLE
请问在自己数据集上训练，大概需要多少数据集？

### ISSUE THREAD

**Issue by Dandelion111** [MichaelFan01/STDC-Seg#52]
请问在自己数据集上训练，大概需要多少数据集？

**Comment by MichaelFan01** [comment]
> 请问在自己数据集上训练，大概需要多少数据集？

这个不好回答，这分具体任务啊，很难预估

**Comment by Dandelion111** [comment]
> > 请问在自己数据集上训练，大概需要多少数据集？
> 
> 这个不好回答，这分具体任务啊，很难预估

只需要分割一个类别，训练自己的数据集是不是要做成cityscapes的格式？

**Comment by Mobu59** [comment]
> > > 请问在自己数据集上训练，大概需要多少数据集？
> > 
> > 
> > 这个不好回答，这分具体任务啊，很难预估
> 
> 只需要分割一个类别，训练自己的数据集是不是要做成cityscapes的格式？

你好，请问你尝试过在自己的数据集上训练了吗
