### ISSUE TITLE
miou和maxmiou变成了nan和0

### ISSUE THREAD

**Issue by Dandelion111** [MichaelFan01/STDC-Seg#54]
![image](https://user-images.githubusercontent.com/48303408/132840876-3424e8aa-3899-4396-9570-24d2e204fccc.png)
请问为啥训练的时候miou和maxmiou变成了nan和0

**Comment by Dandelion111** [comment]
用cityscapes和自己的数据集都这样，大佬这是啥问题

**Comment by li1508858433** [comment]
您好，我现在跑camvid数据集，也遇到和您一样的问题，请问您解决了吗

**Comment by li1508858433** [comment]
> 您好，我现在跑camvid数据集，也遇到和您一样的问题，请问您解决了吗

**Comment by lyxbyr** [comment]
您好，我用自己的数据集也会存在这样的问题，请问下解决了吗
