### ISSUE TITLE
ImportError: No module named 'inplace_abn'  

### ISSUE THREAD

**Issue by chen1234520** [MichaelFan01/STDC-Seg#63]
File "/root/chenguang/anaconda3/envs/STDC/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

  File "/root/chenguang/anaconda3/envs/STDC/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 962, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension 'inplace_abn': b"[1/5] /home/usr/local/cuda/bin/nvcc

    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'inplace_abn'

**Comment by 2653888596** [comment]
May i ask you, I also encountered this problem, is this problem solved?

**Comment by zjsun7** [comment]
> 

请问问题解决了吗。我也遇到类似的问题

**Comment by zjsun7** [comment]
> May i ask you, I also encountered this problem, is this problem solved?

您好，请问问题解决了吗，我也遇到类似的问题？

**Comment by zjsun7** [comment]
> File "/root/chenguang/anaconda3/envs/STDC/lib/python3.5/subprocess.py", line 398, in run output=stdout, stderr=stderr) subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1
> 
> During handling of the above exception, another exception occurred:
> 
> File "/root/chenguang/anaconda3/envs/STDC/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 962, in _build_extension_module raise RuntimeError(message) RuntimeError: Error building extension 'inplace_abn': b"[1/5] /home/usr/local/cuda/bin/nvcc
> 
> ```
> raise ImportError(_ERR_MSG.format(name), name=name)
> ```
> 
> ImportError: No module named 'inplace_abn'

请问您解决了吗

**Comment by zjsun7** [comment]
完美解决，放弃inplace_abn ，将所有的inplace_abn替换为官方bn。

**Comment by woxiangrinyb** [comment]
什么是官方bn？

**Comment by woxiangrinyb** [comment]
> 完美解决，放弃inplace_abn ，将所有的inplace_abn替换为官方bn。

老哥 什么叫官方bn

**Comment by JJY0710** [comment]
请问具体怎么更换的，没看懂啊

**Comment by phk1042791021** [comment]
> 请问具体怎么更换的，没看懂啊

你看哪里用了inplace_abn
换成nn.Batchnorm2d

**Comment by phk1042791021** [comment]
> > 完美解决，放弃inplace_abn ，将所有的inplace_abn替换为官方bn。
> 
> 老哥 什么叫官方bn

nn.Batchnorm2d

**Comment by DuyguSerbes** [comment]
COuld you please rewrite the solution in English?

**Comment by Mobu59** [comment]
> COuld you please rewrite the solution in English?

A simple brute force approach is to replace all inplace_abn with nn.BatchNorm2d
