### ISSUE TITLE
Visualization and Test speed

### ISSUE THREAD

**Issue by yangpanquan** [MichaelFan01/STDC-Seg#64]
Hi, it's a excellent work! But I meet some questions.
Q1: Can you upload your code of  visualization about  spatial path and stage3 with detail guidence?
Q2: My speed is 93 FPS about STDC2-Seg50 on 2080Ti, I just get a half of your result 188.6 FPS.Can you upload your code about testing speed?
Q3: Can you upload the code of calculating params and flops?

**Comment by alittledou** [comment]
> Hi, it's a excellent work! But I meet some questions. Q1: Can you upload your code of visualization about spatial path and stage3 with detail guidence? Q2: My speed is 93 FPS about STDC2-Seg50 on 2080Ti, I just get a half of your result 188.6 FPS.Can you upload your code about testing speed? Q3: Can you upload the code of calculating params and flops?

请问您得到解决了吗，特别是第一个问题，空间路径的可视化代码
