### ISSUE TITLE
STDC backbone for imagenet

### ISSUE THREAD

**Issue by jjxxmiin** [MichaelFan01/STDC-Seg#73]
Thanks for the good work.

How to train STDC backbone on ImageNet?

I think the STDC backbone consists of Stage 1 to Stage 5.

Then, is the STDC backbone for the imagenet created by attaching a fully connected layer to the last global average pooling?

**Comment by Asthestarsfalll** [comment]
https://github.com/MichaelFan01/STDC-Seg/blob/master/nets/stdcnet.py#L195
I think it's for ImageNet classification.

**Comment by jjxxmiin** [comment]
Many Thanks!!

I understood it.
