### ISSUE TITLE
关于Cityscapes测试集mIOU为nan的问题

### ISSUE THREAD

**Issue by zi-ming** [MichaelFan01/STDC-Seg#89]
你好，非常感谢你开源出色的工作，本人在跑Cityscapes测试集的时候遇到最终评估的mIOU为nan的情况，请问除了改mode，还要改其他地方吗？望解答，谢谢！

**Comment by ayinaaaaaa** [comment]
> 你好，非常感谢你开源出色的工作，本人在跑Cityscapes测试集的时候遇到最终评估的mIOU为nan的情况，请问除了改mode，还要改其他地方吗？望解答，谢谢！

你好，请问您解决这个问题了吗

**Comment by li1508858433** [comment]
你好，文件有跑测试集的代码吗？
