### ISSUE TITLE
请问有没有细节真值图detail GT 的可视化代码

### ISSUE THREAD

**Issue by alittledou** [MichaelFan01/STDC-Seg#97]
请问有没有细节真值图detail GT 的可视化代码
![image](https://user-images.githubusercontent.com/33368818/221342398-f64ea1c6-d824-4eb8-8cf0-5df388a6dd87.png)

**Comment by li1508858433** [comment]
您好，请问您现在有细节直值图的代码了吗

**Comment by alittledou** [comment]
你好，这是自动回复邮件。你的邮件我已收到，我将尽快给你回复。
